using System.Collections.Generic;

namespace PixelAssetGenerator.Models;

/// <summary>Permission mode for AI agent execution.</summary>
public enum AiPermissionMode
{
    Execute,         // 执行 — normal full execution
    Plan,            // 计划 — analysis only, no tool execution
    SkipPermissions  // 跳过权限 — execute without any restrictions
}

/// <summary>创作阶段：构图→物件→材质→调整</summary>
public enum CreationPhase
{
    /// <summary>未指定 / 混合</summary>
    General,
    /// <summary>构图：确定整体布局、对称性、比例、边框</summary>
    Composition,
    /// <summary>物件：添加主要视觉元素、形状、图案</summary>
    Object,
    /// <summary>材质：赋予质感、纹理细节、颜色填充</summary>
    Material,
    /// <summary>调整：光影、颜色修正、效果叠加</summary>
    Adjustment
}

/// <summary>分层任务计划中的单个步骤</summary>
public sealed class LayeredTaskStep
{
    public string Description { get; set; } = "";
    public string Status { get; set; } = "pending"; // pending, in_progress, completed, failed
    public CreationPhase Phase { get; set; } = CreationPhase.General;
    /// <summary>工具调用记录（跟踪执行进度）</summary>
    public List<string> ToolCallIds { get; set; } = new();
}

/// <summary>分层任务计划</summary>
public sealed class LayeredPlan
{
    public string Title { get; set; } = "";
    public string RawMarkdown { get; set; } = "";
    public List<LayeredTaskStep> Steps { get; set; } = new();
    public int CurrentStepIndex { get; set; } = -1;

    /// <summary>按阶段分组的步骤</summary>
    public Dictionary<CreationPhase, List<LayeredTaskStep>> StepsByPhase
    {
        get
        {
            var dict = new Dictionary<CreationPhase, List<LayeredTaskStep>>();
            foreach (var step in Steps)
            {
                if (!dict.ContainsKey(step.Phase))
                    dict[step.Phase] = new List<LayeredTaskStep>();
                dict[step.Phase].Add(step);
            }
            return dict;
        }
    }

    /// <summary>整体完成度百分比 (0.0 ~ 1.0)</summary>
    public double Progress
    {
        get
        {
            if (Steps.Count == 0) return 0;
            int done = 0;
            foreach (var s in Steps)
                if (s.Status == "completed" || s.Status == "failed") done++;
            return (double)done / Steps.Count;
        }
    }

    /// <summary>当前阶段的名称</summary>
    public string CurrentPhaseName
    {
        get
        {
            if (CurrentStepIndex < 0 || CurrentStepIndex >= Steps.Count)
                return "";
            return PhaseDisplayName(Steps[CurrentStepIndex].Phase);
        }
    }

    public static string PhaseDisplayName(CreationPhase phase) => phase switch
    {
        CreationPhase.Composition => "构图",
        CreationPhase.Object => "物件",
        CreationPhase.Material => "材质",
        CreationPhase.Adjustment => "调整",
        _ => "通用"
    };
}

/// <summary>Represents an MD task plan generated by the AI.</summary>
public sealed class MdTaskPlan
{
    public string Title { get; set; } = "";
    public string RawMarkdown { get; set; } = "";
    public List<MdTaskStep> Steps { get; set; } = new();
    public int CurrentStepIndex { get; set; } = -1;

    /// <summary>整体完成度 (0.0 ~ 1.0)</summary>
    public double Progress
    {
        get
        {
            if (Steps.Count == 0) return 0;
            int done = 0;
            foreach (var s in Steps)
                if (s.Status == "completed" || s.Status == "failed") done++;
            return (double)done / Steps.Count;
        }
    }
}

public sealed class MdTaskStep
{
    public string Description { get; set; } = "";
    public string Status { get; set; } = "pending"; // pending, in_progress, completed, failed
}

/// <summary>
/// 计划更新指令：由 AI 通过工具调用发出的结构化计划进度更新。
/// </summary>
public sealed class PlanUpdateCommand
{
    /// <summary>步骤索引（从 0 开始），或 -1 表示按描述匹配</summary>
    public int StepIndex { get; set; } = -1;

    /// <summary>当 StepIndex == -1 时，用此描述匹配步骤</summary>
    public string? StepDescription { get; set; }

    /// <summary>新状态: pending / in_progress / completed / failed</summary>
    public string Status { get; set; } = "in_progress";

    /// <summary>可选的阶段名，用于分层计划中的阶段切换</summary>
    public string? PhaseName { get; set; }

    /// <summary>当前步骤说明文本（可选，用于 AI 更新描述细节）</summary>
    public string? CurrentStepNote { get; set; }
}
